server:
  port: 8181
  
spring:
  application:
    name: api-gateway
    
hostname:
  server: localhost

#routers
zuul:
    routes:
        customer:
            path: /api/customer-service/**
            service-id: customer-service
            url: http://${hostname.server}:8088/
        product:
            path: /api/product-service/**
            service-id: product-service
            url: http://${hostname.server}:8081/
        transaction:
            path: /api/transaction-service/**
            service-id: transaction-service
            url: http://${hostname.server}:8082/
        representative:
            path: /api/representative-service/**
            service-id: representative-service
            url: http://${hostname.server}:8083/
        movement:
            path: /api/movement-service/**
            service-id: movement-service
            url: http://${hostname.server}:8085/
        credit:
            path: /api/credit-service/**
            service-id: credit-service
            url: http://${hostname.server}:8086/
        creditcard:
            path: /api/creditcard-service
            service-id: creditcard-service
            url: http://${hostname.server}:8087/
        yanki:
            path: /api/yanki-service
            service-id: yanki-service
            url: http://${hostname.server}:8089/
        p2p:
            path: /api/p2p-service
            service-id: p2p-service
            url: http://${hostname.server}:8084/
        
